import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillTwitterCircle,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import profilePic from "../../public/profilePic.jpeg";
import design from "../../public/design.png";
import code from "../../public/code.png";
import consulting from "../../public/consulting.png";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jason Williams Portfolio</title>
        <meta name="description" content="generated by creator"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Jason Williams</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode) } className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://docs.google.com/document/d/e/2PACX-1vQor9tv0dKHs1OyhjQpUR33_JqC7BCZOA5xgZQGgG7qFsL7rg3hFiET2MWSinTautJ5jeroE3TauL9m/pub"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jason Williams
            </h2>
            <h3 className="text-2xl font-burtons py-2 md:text-3xl dark:text-white">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-xl mx-auto dark:text-white">
              Freelancer providing unmatched service for all of your programming
              and design needs.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            {/* <AiFillTwitterCircle /> */}
            <a href="https://www.linkedin.com/in/jasonlovestowork95/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/imjaybear">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 md:h-96 w-96">
            {/* <Image src={profilePic} fill cover></Image> */}
          </div>
        </section>
        <section>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <h3 className="text-3xl py-1 text-center font-burtons dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 text-center dark:text-gray-300">
              Hi there! 👋 My name is Jason, and I'm a passionate and dedicated
              web developer based in the Chicagoland Area. I have a BBA from
              Indiana University, graduating in 2019. I recently completed the
              Full Stack Web Development Program at Thinkful. Here I developed
              proficiency in HTML, CSS, JavaScript, React, Node.js as well as
              many other technologies. I'm passionate about creating beautiful,
              user-friendly, and responsive applications that solve real-world
              problems and meet the needs of my clients. When I'm not coding,
              you can find me pursuing my other passions: gaming 🎮 and
              jiu-jitsu 🥋. I've been an avid gamer for since I was a child, and
              I actually first got introduced to coding through gaming! I also
              practice jiu-jitsu regularly, which helps me stay focused,
              disciplined, and mentally sharp. Originally from Chicago, I bring
              a Midwestern work ethic and a friendly, collaborative spirit to
              every project I take on. I'm always looking for new challenges and
              opportunities to learn and grow, and I'm excited to work with you
              to bring your ideas to life. Let's build something amazing
              together!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-xl font-burtons font-medium pt-8 pb-2 dark:text-white">
                Website Designs
              </h3>
              <p className="py-1 dark:text-gray-300">
                Elevate your brand and stand out from the crowd! Using the
                latest design tools and core design theory, I create stunning
                visuals that captures your brand's personality and communicates
                your message effectively. From logos and business cards to
                website interfaces and social media graphics, I provide custom
                and professional designs that engage and impress your audience.
              </p>
              <h4 className="py-4 font-burtons text-xl text-teal-600">
                Design tools I use
              </h4>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">Illustrator</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">Blender</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-xl font-burtons font-medium pt-8 pb-2 dark:text-white">
                Coding
              </h3>
              <p className="py-2 dark:text-gray-300">
                As a developer, I specialize in offering coding as a service for
                businesses and individuals looking to bring their ideas to life.
                Whether you need a modern and responsive website built from
                scratch, a custom web application tailored to your business
                needs, or ongoing support and maintenance for your existing
                codebase, I can help!
              </p>
              <h4 className="py-4 font-burtons text-xl text-teal-600">
                Technologies I use
              </h4>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">
                Javascript (React.js, Next.js, etc.)
              </p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">HTML5 & CSS</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">Python</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300">PostgreSQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-xl font-burtons font-medium pt-8 pb-2 dark:text-white">
                Consulting/Tutoring
              </h3>
              <p className="py-2 dark:text-gray-300">
                Ready to take your web development and coding skills to the next
                level? Look no further! With my expert consulting and tutoring
                services, I can help you master the latest technologies and best
                practices in web development and coding.
              </p>
              <h4 className="py-4 font-burtons text-xl text-teal-600">
                Design tools I use
              </h4>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300
              ">Photoshop</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300
              ">Illustrator</p>
              <p className="text-gray-800 text-sm py-1 dark:text-gray-300
              ">Blender</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 font-burtons dark:text-white">Portfolio</h3>

            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image
                  src={web1}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web2}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web3}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web4}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
              <div className=" basis-1/3 flex-1">
                <Image
                  src={web5}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web6}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  responsive
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
